services:
  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    restart: unless-stopped

  backend:
    image: aminataci/portfolio-backend:latest
    ports:
      - "5000:5000"
    env_file:
      - ./porfolio-expessjs-mongodb/.env
    depends_on:
      - mongodb
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    image: aminataci/portfolio-frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

volumes:
  mongo-data:

networks:
  app-network:
